config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  get 'toppage', to: 'toppages#index'
  resources :users do
    member do
      get :followings
      get :followers
      get :likes
      get :joinings
    end
  end
  
  resources :groups do
    member do
      get :joineds
      resources :group_posts, only: [:create, :edit, :destroy]
    end
  end
  
  resources :posts
  resources :group_posts, only: [:new]
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :group_users, only: [:create, :destroy]
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :group_users
  has_many :joineds, through: :group_users, source: :user
  has_many :group_posts, dependent: :destroy

  validates :name, presence: true, length: { maximum: 15 }
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:edit, :destroy]
  before_action :set_group, only: [:show, :edit, :update, :destroy, :joineds]
  
  def index
    @groups = Group.order(id: :desc).page(params[:page]).per(25)
  end
  
  def show
    @grouppost = @group.group_posts.build 
    @groupposts = @group.group_posts.order(id: :desc).page(params[:page]).per(25)
  end
  
  def new
    @group = Group.new
  end
  
  def create
    @group = current_user.groups.build(group_params)
    if @group.save
      flash[:success] = 'グループを作成しました。'
      redirect_to groups_url
    else
      @groups = current_user.groups.order(id: :desc).page(params[:page])
      flash.now[:danger] = 'グループの作成に失敗しました。'
      render 'groups/new'
    end
  end
  
  def edit
  end
  
  def update
    if @group.update(group_params)
      flash[:success] = 'グループ名は正常に更新されました'
      redirect_to groups_url
    else
      flash.now[:danger] = 'グループ名は更新されませんでした'
      render :edit
    end
  end
  
  def destroy
    @group.destroy
    flash[:success] = 'グループを削除しました。'
    redirect_back(fallback_location: root_path)
  end
  
  def joineds
    @joineds = @group.joineds.page(params[:page])
  end
  
  private
  
  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, :content)
  end
  
  def correct_user
    @group = current_user.groups.find_by(id: params[:id])
    unless @group
      redirect_to root_url
    end
  end
end

app/views/groups/_groups.html.erb
<ul class="list-unstyled">
  <% groups.each do |group| %>
    <li class="media border-bottom pb-2 pt-2">
      <div class="media-body">
        <div>
          <p><%= link_to group.name, group_path(group) %></p>
          <p>グループ詳細：<%= group.content %></p>
        </div>
        <div class="row mt-3">
          <span class="ml-3">
            <%= render 'group_users/join_button', group: group %>
          </span>
          <span class="ml-1">
            <% if current_user == group.user %>
              <%= link_to "編集", edit_group_path(group), class: 'btn btn-primary btn-sm' %>
            <% end %>
          </span>
          <span class="ml-1">
            <% if current_user == group.user %>
              <%= link_to "消去", group, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-sm' %>
            <% end %>
          </span>
        </div>
      </div>
    </li>
  <% end %>
  <%= paginate groups %>
</ul>

app/views/groups/edit.html.erb
<%= form_with(model: @group, local: true) do |f| %>
  <div class="form-group">
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :content, 'グループ詳細' %>
    <%= f.text_field :content, class: 'form-control' %>
  </div>
  <div class="row">
    <div class="col-sm-2 offset-sm-8">
      <%= link_to 'キャンセル', groups_path, class: "btn btn-link btn-block" %>
    </div>
    <div class="col-sm-2">
      <%= f.submit 'Post', class: 'btn btn-primary btn-block' %>
    </div>
  </div>
<% end %>

app/views/groups/index.html.erb
<div class="row border p-3">
  <aside class="col-2">
    <ul class="list-unstyled mt-3">
      <%= render 'layouts/link_list' %>
    </ul>
  </aside>
  <div class="col-10 border-left">
    <ul class="nav nav-pills nav-justified mb-3">
      <li class="nav-item"><a href="<%= posts_path %>" class="nav-link <%= 'active' if current_page?(posts_path) %>">投稿一覧</a></li>
      <li class="nav-item"><a href="<%= users_path %>" class="nav-link <%= 'active' if current_page?(users_path) %>">ユーザ一覧</a></li>
      <li class="nav-item"><a href="<%= groups_path %>" class="nav-link <%= 'active' if current_page?(groups_path) %>">グループ一覧</a></li>
    </ul>
    <div>
      <div class="row col-10 mb-5">
        <%= render 'groups/groups', groups: @groups %>
      </div>
      <%= link_to "新規グループの作成", new_group_path, class: 'btn btn-primary btn-sm' %>
    </div>
  </div>
</div>

app/views/groups/joineds.html.erb
<div class="row border p-3">
  <aside class="col-2">
    <%= render 'layouts/link_list' %>
  </aside>
  <div class="col-10 border-left">
    <h4 class="text-center">【参加グループ：<%= @group.name %>】</h4>
    <ul class="nav nav-pills nav-justified mb-3">
      <li class="nav-item"><a href="<%= group_path(@group) %>" class="nav-link <%= 'active' if current_page?(group_path(@group)) %>">投稿一覧</a></li>
      <li class="nav-item"><a href="<%= joineds_group_path(@group) %>" class="nav-link <%= 'active' if current_page?(joineds_group_path(@group)) %>">参加ユーザ一覧</a></li>
    </ul>
    <div>
      <div class="row col-10">
         <%= render 'users/users', users: @joineds %>
      </div>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<%= form_with(model: @group, local: true) do |f| %>
  <div class="form-group">
    <%= f.label :name, 'グループ名' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :content, 'グループ詳細' %>
    <%= f.text_field :content, class: 'form-control' %>
  </div>
  <div class="row">
    <div class="col-sm-2 offset-sm-8">
      <%= link_to 'キャンセル', groups_path, class: "btn btn-link btn-block" %>
    </div>
    <div class="col-sm-2">
      <%= f.submit 'グループ作成', class: 'btn btn-primary btn-block' %>
    </div>
  </div>
<% end %>

app/views/groups/show.html.erb
<% if @group.joineds.include?(current_user) %>
  <div class="row border p-3">
    <aside class="col-2">
      <%= render 'layouts/link_list' %>
    </aside>
    <div class="col-10 border-left">
      <h4 class="text-center">【参加グループ：<%= @group.name %>】</h4>
        <div class="row border rounded m-3">
          <h5 class="col-sm-12 mt-3">【<%= @group.name %>】の詳細</h5>
          <h6 class="col-sm-12 mt-3"><%= @group.content%></h6>
        </div>
      <ul class="nav nav-pills nav-justified mb-3">
        <li class="nav-item"><a href="<%= group_path(@group) %>" class="nav-link <%= 'active' if current_page?(group_path(@group)) %>">投稿一覧</a></li>
        <li class="nav-item"><a href="<%= joineds_group_path(@group) %>" class="nav-link <%= 'active' if current_page?(joineds_group_path(@group)) %>">参加ユーザ一覧</a></li>
      </ul>
      <div>
        <div class="row m-1">
          <%= form_with(model: @grouppost, local: true) do |f| %>
            <div class="form-group">
              <%= f.text_area :content, class: 'form-control', rows: 5, cols: 100 %>
            </div>
            <div class="row offset-11">
              <div>
                <%= f.submit 'Post', class: 'btn btn-primary btn-block' %>
              </div>
            </div>
            <% end %>
          <%= render 'group_posts/group_posts', posts: @groupposts %>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <div class="row border p-3">
    <aside class="col-2">
      <%= render 'layouts/link_list' %>
    </aside>
    <div class="col-10 border-left">
      <h4 class="text-center">【グループ名：<%= @group.name %>】</h4>
      <div class="row border rounded m-3">
        <h5 class="col-sm-12 mt-3">【<%= @group.name %>】の詳細</h5>
        <h6 class="col-sm-12 mt-3"><%= @group.content%></h6>
      </div>
    </div>
  </div>
<% end %>