config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  get 'toppage', to: 'toppages#index'
  resources :users do
    member do
      get :followings
      get :followers
      get :likes
      get :joinings
    end
  end
  
  resources :groups do
    member do
      get :joineds
      resources :group_posts, only: [:create, :edit, :destroy]
    end
  end
  
  resources :posts
  resources :group_posts, only: [:new]
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :group_users, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :goal, length: { maximum: 255 }
  validates :status, length: { maximum: 255 }
  
  has_many :posts
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverses_of_relationship, source: :user
  has_many :favorites
  has_many :likes, through: :favorites, source: :post
  has_many :groups
  has_many :group_users
  has_many :joinings, through: :group_users, source: :group
  has_many :group_posts

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end
  
  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end
  
  def following?(other_user)
    self.followings.include?(other_user)
  end
  
  def feed_posts
    Post.where(user_id: self.following_ids)
  end
  
  def favorite(post)
    self.favorites.find_or_create_by(post_id: post.id)
  end

  def unfavorite(post)
    favorite = self.favorites.find_by(post_id: post.id)
    favorite.destroy if favorite
  end

  def likes?(post)
    self.likes.include?(post)
  end
  
  def join(group)
    self.group_users.find_or_create_by(group_id: group.id)
  end
  
  def unjoin(group)
    join = self.group_users.find_by(group_id: group.id)
    join.destroy if join
  end
  
  def joinings?(group)
    self.joinings.include?(group)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :edit, :followings, :followers]
  before_action :correct_user, only: [:edit, :destroy]
  before_action :set_user, only: [:show, :edit, :update, :destroy, :followings, :followers, :likes, :joinings]
  
  def index
    @users = User.order(id: :desc).page(params[:page]).per(25)
  end

  def show
    @posts = @user.posts.order(id: :desc).page(params[:page])
    counts(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @user.update(user_params)
      flash[:success] = 'プロフィールは正常に更新されました。'
      redirect_to @user
    else
      flash.now[:danger] = 'プロフィールの更新に失敗しました。'
      render :edit
    end
  end
  
  def destroy
    @user.destroy

    flash[:success] = 'ユーザは正常に削除されました'
    redirect_to toppage_url
  end
  
  def followings
    @followings = @user.followings.page(params[:page])
  end
  
  def followers
    @followers = @user.followers.page(params[:page])
  end
  
  def likes
    @likes = @user.likes.page(params[:page])
  end
  
  def joinings
    @joinings = @user.joinings.page(params[:page])
  end

  private
  
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :goal, :status)
  end
  
  def correct_user
    @user = User.find(params[:id])
    unless current_user == @user
      redirect_to root_url
    end
  end
end

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="list-unstyled">
    <% users.each do |user| %>
      <li class="border-bottom pt-2 pb-2">
        <div class="media-body">
          <div>
            <p><%= link_to user.name, user_path(user) %></p>
            <p>目標：<%= user.goal %></p>
            <p>プロフィール：<%= user.status %></p>
          </div>
          <div> 
            <%= render 'relationships/follow_button', user: user %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/edit.html.erb
<div class="row border p-3">
  <div class="col-sm-2 border">
    <ul class="list-unstyled mt-3">
      <%= render 'layouts/link_list' %>
    </ul>
  </div>
  <div class="col-sm-10 p-3 border">
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :goal, '目標' %>
        <%= f.text_field :goal, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :status, 'プロフィール' %>
        <%= f.text_field :status, class: 'form-control' %>
      </div>

      <div class="col-sm-4 offset-sm-4 mb-3">
      <%= f.submit '登録', class: 'btn btn-primary btn-block' %>
      </div>
      
      <div class="col-sm-4 offset-sm-8 text-right">
        <%= link_to 'プロフィール詳細に戻る', user_path %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<div class="row border p-3">
  <aside class="col-2">
    <%= render 'layouts/link_list' %>
    <% if current_user == @user %>
      <ul class="list-unstyled mt-3">
        <li class="mt-3"><%= link_to 'ユーザの削除', @user, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %></li>
      </ul>
    <% end %>
  </aside>
  <div class="col-10 border-left">
    <div class="row p-3">
      <div class="col-4">
        <h4 class="text-left">ユーザ：<%= @user.name %></h4>
      </div>
      <div class="col-3 offset-5">
        <% if current_user == @user %>
          <%= link_to 'プロフィール編集', edit_user_path, class: "btn btn-light"%></li>
        <% end %>
      </div>
    </div>
    <div class="row border rounded m-3">
      <h5 class="col-sm-12 mt-3"><%= @user.name %>の目標</h5>
      <h6 class="col-sm-12 mt-3"><%= @user.goal%></h6>
      <h5 class="col-sm-12 mt-5"><%= @user.name %>のプロフィール</h5>
      <h6 class="col-sm-12 mt-3 mb-3"><%= @user.status %></h6>
    </div>
    <ul class="nav nav-pills nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">投稿</a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">Follow</a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">Follower</a></li>
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">お気に入り</a></li>
      <li class="nav-item"><a href="<%= joinings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(joinings_user_path(@user)) %>">参加グループ</a></li>
    </ul>
    <div class="row m-3">
      <%= render 'users', users: @followers %>
    </div>
  </div>
</div>

app/views/users/followings.html.erb
<div class="row border p-3">
  <aside class="col-2">
    <%= render 'layouts/link_list' %>
    <% if current_user == @user %>
      <ul class="list-unstyled mt-3">
        <li class="mt-3"><%= link_to 'ユーザの削除', @user, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %></li>
      </ul>
    <% end %>
  </aside>
  <div class="col-10 border-left">
    <div class="row p-3">
      <div class="col-4">
        <h4 class="text-left">ユーザ：<%= @user.name %></h4>
      </div>
      <div class="col-3 offset-5">
        <% if current_user == @user %>
          <%= link_to 'プロフィール編集', edit_user_path, class: "btn btn-light"%></li>
        <% end %>
      </div>
    </div>
    <div class="row border rounded m-3">
      <h5 class="col-sm-12 mt-3"><%= @user.name %>の目標</h5>
      <h6 class="col-sm-12 mt-3"><%= @user.goal%></h6>
      <h5 class="col-sm-12 mt-5"><%= @user.name %>のプロフィール</h5>
      <h6 class="col-sm-12 mt-3 mb-3"><%= @user.status %></h6>
    </div>
    <ul class="nav nav-pills nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">投稿</a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">Follow</a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">Follower</a></li>
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">お気に入り</a></li>
      <li class="nav-item"><a href="<%= joinings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(joinings_user_path(@user)) %>">参加グループ</a></li>
    </ul>
    <div class="row m-3">
      <%= render 'users', users: @followings %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="row border p-3">
  <aside class="col-sm-2">
    <ul class="list-unstyled mt-3">
      <%= render 'layouts/link_list' %>
    </ul>
  </aside>
  <div class="col-sm-10 border-left">
    <ul class="nav nav-pills nav-justified mb-3">
      <li class="nav-item"><a href="<%= posts_path %>" class="nav-link <%= 'active' if current_page?(posts_path) %>">投稿一覧</a></li>
      <li class="nav-item"><a href="<%= users_path %>" class="nav-link <%= 'active' if current_page?(users_path) %>">ユーザ一覧</a></li>
      <li class="nav-item"><a href="<%= groups_path %>" class="nav-link <%= 'active' if current_page?(groups_path) %>">グループ一覧</a></li>
    </ul>
    <div>
      <div class="row col-sm-10">
        <%= render 'users', users: @users %>
      </div>
    </div>
  </div>
</div>

app/views/users/joinings.html.erb
<div class="row border p-3">
  <aside class="col-2">
    <%= render 'layouts/link_list' %>
    <% if current_user == @user %>
      <ul class="list-unstyled mt-3">
        <li class="mt-3"><%= link_to 'ユーザの削除', @user, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %></li>
      </ul>
    <% end %>
  </aside>
  <div class="col-10 border-left">
    <div class="row p-3">
      <div class="col-sm-4">
        <h4 class="text-left">ユーザ：<%= @user.name %></h4>
      </div>
      <div class="col-3 offset-5">
        <% if current_user == @user %>
          <%= link_to 'プロフィール編集', edit_user_path, class: "btn btn-light"%></li>
        <% end %>
      </div>
    </div>
    <div class="row border rounded m-3">
      <h5 class="col-sm-12 mt-3"><%= @user.name %>の目標</h5>
      <h6 class="col-sm-12 mt-3"><%= @user.goal%></h6>
      <h5 class="col-sm-12 mt-5"><%= @user.name %>のプロフィール</h5>
      <h6 class="col-sm-12 mt-3 mb-3"><%= @user.status %></h6>
    </div>
    <ul class="nav nav-pills nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">投稿</a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">Follow</a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">Follower</a></li>
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">お気に入り</a></li>
      <li class="nav-item"><a href="<%= joinings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(joinings_user_path(@user)) %>">参加グループ</a></li>
    </ul>
    <div class="row m-3">
      <%= render 'groups/groups', groups: @joinings %>
    </div>
  </div>
</div>

app/views/users/likes.html.erb
<div class="row border p-3">
  <aside class="col-2">
    <%= render 'layouts/link_list' %>
    <% if current_user == @user %>
      <ul class="list-unstyled mt-3">
        <li class="mt-3"><%= link_to 'ユーザの削除', @user, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %></li>
      </ul>
    <% end %>
  </aside>
  <div class="col-10 border-left">
    <div class="row p-3">
      <div class="col-sm-4">
        <h4 class="text-left">ユーザ：<%= @user.name %></h4>
      </div>
      <div class="col-3 offset-5">
        <% if current_user == @user %>
          <%= link_to 'プロフィール編集', edit_user_path, class: "btn btn-light"%></li>
        <% end %>
      </div>
    </div>
    <div class="row border rounded m-3">
      <h5 class="col-sm-12 mt-3"><%= @user.name %>の目標</h5>
      <h6 class="col-sm-12 mt-3"><%= @user.goal%></h6>
      <h5 class="col-sm-12 mt-5"><%= @user.name %>のプロフィール</h5>
      <h6 class="col-sm-12 mt-3 mb-3"><%= @user.status %></h6>
    </div>
    <ul class="nav nav-pills nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">投稿</a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">Follow</a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">Follower</a></li>
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">お気に入り</a></li>
      <li class="nav-item"><a href="<%= joinings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(joinings_user_path(@user)) %>">参加グループ</a></li>
    </ul>
    <div class="row m-3">
      <%= render 'posts/posts', posts: @likes %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="row border border-dark col-sm-10 offset-sm-1">
  <div class="col-sm-12 mt-3">
    <h2>ユーザ登録</h2>
  </div>
  <div class="col-sm-12 mt-3">

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Password(確認のためもう一度入力してください。)' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      
      <div class="col-sm-4 offset-sm-4 mb-3">
      <%= f.submit '登録', class: 'btn btn-primary btn-block' %>
      </div>
    
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row border p-3">
  <aside class="col-2">
    <%= render 'layouts/link_list' %>
    <% if current_user == @user %>
      <ul class="list-unstyled mt-3">
        <li class="mt-3"><%= link_to 'ユーザの削除', @user, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %></li>
      </ul>
    <% end %>
  </aside>
  <div class="col-10 border-left">
    <div class="row p-3">
      <div class="col-4">
        <h4 class="text-left">ユーザ：<%= @user.name %></h4>
      </div>
      <div class="col-3 offset-5">
        <% if current_user == @user %>
          <%= link_to 'プロフィール編集', edit_user_path, class: "btn btn-light"%></li>
        <% end %>
      </div>
    </div>
    <div class="row border rounded m-3">
      <h5 class="col-sm-12 mt-3"><%= @user.name %>の目標</h5>
      <h6 class="col-sm-12 mt-3"><%= @user.goal%></h6>
      <h5 class="col-sm-12 mt-5"><%= @user.name %>のプロフィール</h5>
      <h6 class="col-sm-12 mt-3 mb-3"><%= @user.status %></h6>
    </div>
    <ul class="nav nav-pills nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">投稿</a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">Follow</a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">Follower</a></li>
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">お気に入り</a></li>
      <li class="nav-item"><a href="<%= joinings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(joinings_user_path(@user)) %>">参加グループ</a></li>
    </ul>
    <div class="row m-3">
      <%= render 'posts/posts', posts: @posts %>
    </div>
  </div>
</div>