config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  get 'toppage', to: 'toppages#index'
  resources :users do
    member do
      get :followings
      get :followers
      get :likes
      get :joinings
    end
  end
  
  resources :groups do
    member do
      get :joineds
      resources :group_posts, only: [:create, :edit, :destroy]
    end
  end
  
  resources :posts
  resources :group_posts, only: [:new]
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :group_users, only: [:create, :destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :favorites
  has_many :likeds, through: :favorites, source: :user
  
  validates :content, presence: true, length: { maximum: 140 }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:edit, :destroy]
  
  def index
    @posts = Post.order(id: :desc).page(params[:page]).per(25)
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = 'メッセージを投稿しました。'
      redirect_to root_url
    else
      @posts = current_user.posts.order(id: :desc).page(params[:page])
      flash.now[:danger] = 'メッセージの投稿に失敗しました。'
      render 'posts/new'
    end
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      flash[:success] = 'メッセージは正常に更新されました'
      redirect_to posts_url
    else
      flash.now[:danger] = 'メッセージは更新されませんでした'
      render :edit
    end
  end

  def destroy
    @post.destroy
    flash[:success] = 'メッセージを削除しました。'
    redirect_back(fallback_location: root_path)
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end
  
  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    unless @post
      redirect_to root_url
    end
  end
end

app/views/posts/_posts.html.erb
<ul class="list-unstyled">
  <% posts.each do |post| %>
    <li class="media border-bottom pt-2 pb-2">
      <div class="media-body">
        <div>
          <%= link_to post.user.name, user_path(post.user) %> <span class="text-muted"><%= post.created_at.strftime("%Y-%m-%d %H:%M") %></span>
        </div>
        <div>
          <p><%= post.content %></p>
        </div>
        <div class="row">
          <span class="ml-3">
            <%= render 'favorites/favorite_button', post: post %>
          </span>
          <span class="ml-1">
            <% if current_user == post.user %>
              <%= link_to "編集", edit_post_path(post), class: 'btn btn-primary btn-sm' %>
            <% end %>
          </span>
          <span class="ml-1">
            <% if current_user == post.user %>
              <%= link_to "消去", post, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-sm' %>
            <% end %>
          </span>
        </div>
      </div>
    </li>
  <% end %>
  <%= paginate posts %>
</ul>

app/views/posts/edit.html.erb
<%= form_with(model: @post, local: true) do |f| %>
  <div class="form-group">
    <%= f.text_area :content, class: 'form-control', rows: 5 %>
  </div>
  <div class="row">
    <div class="col-sm-2 offset-sm-8">
      <%= link_to 'キャンセル', posts_path, class: "btn btn-link btn-block" %>
    </div>
    <div class="col-sm-2">
      <%= f.submit 'Post', class: 'btn btn-primary btn-block' %>
    </div>
  </div>
<% end %>

app/views/posts/index.html.erb
<div class="row border p-3">
  <aside class="col-sm-2">
    <ul class="list-unstyled mt-3">
      <%= render 'layouts/link_list' %>
    </ul>
  </aside>
  <div class="col-sm-10 border-left">
    <ul class="nav nav-pills nav-justified mb-3">
      <li class="nav-item"><a href="<%= posts_path %>" class="nav-link <%= 'active' if current_page?(posts_path) %>">投稿一覧</a></li>
      <li class="nav-item"><a href="<%= users_path %>" class="nav-link <%= 'active' if current_page?(users_path) %>">ユーザ一覧</a></li>
      <li class="nav-item"><a href="<%= groups_path %>" class="nav-link <%= 'active' if current_page?(groups_path) %>">グループ一覧</a></li>
    </ul>
    <div>
      <div class="row col-sm-10">
        <%= render 'posts/posts', posts: @posts %>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<%= form_with(model: @post, local: true) do |f| %>
  <div class="form-group">
    <%= f.text_area :content, class: 'form-control', rows: 5 %>
  </div>
  <div class="row">
    <div class="col-2 offset-8">
      <%= link_to 'キャンセル', posts_path, class: "btn btn-link btn-block" %>
    </div>
    <div class="col-2">
      <%= f.submit 'Post', class: 'btn btn-primary btn-block' %>
    </div>
  </div>
<% end %>