config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  get 'toppage', to: 'toppages#index'
  resources :users do
    member do
      get :followings
      get :followers
      get :likes
      get :joinings
    end
  end
  
  resources :groups do
    member do
      get :joineds
      resources :group_posts, only: [:create, :edit, :destroy]
    end
  end
  
  resources :posts
  resources :group_posts, only: [:new]
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :group_users, only: [:create, :destroy]
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_link_list.html.erb
<div class="mtb-2">
  <h6 class="text-center">ログインユーザー</h6>
  <h6 class="text-center"><%= current_user.name %></h6>
</div>
<ul class="list-unstyled mt-3">
  <li class="mt-3"><%= link_to 'プロフィール詳細', user_path(current_user) %></li>
  <li class="mt-3"><%= link_to 'Follow一覧', followings_user_path(current_user) %></li>
  <li class="mt-3"><%= link_to 'Follower一覧', followers_user_path(current_user) %></li>
  <li class="mt-3"><%= link_to 'お気に入り一覧', likes_user_path(current_user) %></li>
  <li class="mt-3"><%= link_to '参加グループ一覧', joinings_user_path(current_user) %></li>
  <li class="mt-3"><%= link_to '投稿一覧', posts_path %></li>
  <li class="mt-3"><%= link_to 'ユーザ一覧', users_path %></li>
  <li class="mt-3"><%= link_to 'グループ一覧', groups_path %></li>
</ul>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-light bg-light">
    <a class="navbar-brand" href="/">Study Together  〜共に学ぼう〜</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item"><%= link_to '新規投稿', new_post_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link' %></li>
        <% else %>
          <li class="nav-item"><%= link_to 'ユーザ登録', signup_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>StudyTogether</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>